<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>as</string>
	</array>
	<key>name</key>
	<string>ActionScript 3.0</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#packages</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-contents</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#meta-storage-new</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var-declarations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#imports</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.block.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blocks</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#block-contents</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
			</array>
		</dict>
		<key>classes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.actionscript.3</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.actionscript.3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.actionscript.3</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.actionscript.3</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.actionscript.3</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.actionscript.3</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>keyword.other.actionscript.3</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>class header; currently will only capture the first declared interface</string>
					<key>match</key>
					<string>\b(\w*)\s*\b(class)\s+(\w+)(\s+(extends)\s+(\w+\.)*(\w+))?(\s+(implements)\s+(\w+\.)*(\w+))?</string>
					<key>name</key>
					<string>meta.class.header.actionscript.3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.class.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blocks</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#block-contents</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*</string>
					<key>name</key>
					<string>comment.line.double-slash.actionscript.3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(0x[\da-fA-F]+|\d+(\.\d+)?)\b|\.\d+\b</string>
					<key>name</key>
					<string>constant.numeric.actionscript.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|null|this|NaN|undefined|Number\.POSITIVE_INFINITY|Number\.NEGATIVE_INFINITY)\b|(\-)?Infinity\b</string>
					<key>name</key>
					<string>constant.language.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(function)(\s+([sg]et\s+)?(\w*))?\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.actionscript.3</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.actionscript.3</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.actionscript.3</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>function header; maybe improve matching of variable declarations at some point?</string>
					<key>end</key>
					<string>\)((:)\s*(\w+|\*)\b)?</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.actionscript.3</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.actionscript.3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.header.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#meta-storage-var-type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b\w+\b</string>
							<key>name</key>
							<string>variable.parameter.actionscript.3</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>imports</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.storage.actionscript.3</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.actionscript.3</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.actionscript.3</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(import)\s+(\w+\.)*(\w+|\*)(;)?</string>
					<key>name</key>
					<string>meta.import.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(break|case|continue|default|do|while|else|for( each)?|if|return|super|switch|throw|try|catch|finally|while|with)\b</string>
					<key>name</key>
					<string>keyword.control.actionscript.3</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>namespaces</string>
					<key>match</key>
					<string>\b(AS3|flash_proxy|object_proxy)\b</string>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(default xml namespace|import|include|use namespace)\b</string>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(extends|implements)\b</string>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>meta-storage-new</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.actionscript.3</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type.actionscript.3</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(new)\s+((\w+\.)*)(\w+)\b</string>
					<key>name</key>
					<string>meta.storage.type.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>meta-storage-var-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.actionscript.3</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.actionscript.3</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:)\s*(\w+\.)*(\w+)\b</string>
					<key>name</key>
					<string>meta.storage.type.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\+-/\*%\=&amp;~\|^&lt;&gt;!,\?:\.@;]</string>
					<key>name</key>
					<string>keyword.operator.actionscript.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(as|delete|in|instanceof|is|new|typeof)\b</string>
					<key>name</key>
					<string>keyword.operator.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>packages</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.actionscript.3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.package.actionscript.3</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>package header</string>
					<key>match</key>
					<string>\b(package)(\s+[\w\.]+)?</string>
					<key>name</key>
					<string>meta.package.header.actionscript.3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.package.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#classes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#imports</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(class|const|function|interface|namespace|package|var)\b</string>
					<key>name</key>
					<string>storage.type.actionscript.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(dynamic|final|internal|native|override|private|protected|public|static)\b</string>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.actionscript.3</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.actionscript.3</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var-declarations</key>
		<dict>
			<key>begin</key>
			<string>\b(var|const)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.actionscript.3</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>using this to catch meta-storage-var-type, cos otherwise that will also catch literal object declarations. also ending this with a ';' since otherwise I'm thinking it will be a ballache to catch, even though it is not *technically* required to end the line.... complaints on a postcard please.</string>
			<key>end</key>
			<string>;|\bin\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.actionscript.3</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#meta-storage-var-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta-storage-new</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.actionscript.3</string>
</dict>
</plist>
